spring.application.name=hotrohoctapbackend

spring.datasource.url=jdbc:mysql://localhost:3306/hotrohoctap2
spring.datasource.username=root
spring.datasource.password=

#auto create table
spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true

#hotrohoctap2.redis.cache.windows.net:6380,password=ml6CckeNXxSoLVNTTXjxgEAYGWAJmtpYeAzCaIfYV2M=,ssl=True,abortConnect=False

#Cau hinh cho Redis Localhost
#spring.data.redis.host=localhost
#spring.data.redis.port=6379
##spring.redis.ssl=true
#spring.data.redis.repositories.enabled=false
#spring.cache.type=redis
#spring.data.redis.cache-null-values=true


#Cau hinh cho azure redis
#spring.redis.host=hotrohoctap2.redis.cache.windows.net
#spring.redis.port=6379
#spring.redis.password=ml6CckeNXxSoLVNTTXjxgEAYGWAJmtpYeAzCaIfYV2M=
#spring.redis.ssl=false
#spring.redis.repositories.enabled=false
#spring.cache.type=redis
#spring.redis.cache-null-values=true


spring.data.redis.host=hotrohoctap2.redis.cache.windows.net
spring.data.redis.port=6380
spring.data.redis.password=ZwXD4q8sNvVj3tgQZt1HYTYKcnAR2wRb1AzCaNSeYWM=
spring.data.redis.ssl.enabled=true


spring.main.allow-bean-definition-overriding=true

#spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
#mysql://root:wGWMujjciTWuQbefvwGcNIMbQPLRTaGW@roundhouse.proxy.rlwy.net:21003/railway

# Limit video
spring.servlet.multipart.max-file-size=1000MB
spring.servlet.multipart.max-request-size=1000MB

#Cau hình CORS
spring.web.cors.allowed-origins=http://localhost:3000
spring.web.cors.allowed-methods=GET,POST,PUT,DELETE,OPTIONS
spring.web.cors.allowed-headers=*


