docx4j.jaxb.marshal.opcode=2
docx4j.jaxb.marshal.ooxml.enable=true
docx4j.openpackaging.io.save_flat_opc=true

docx4j.Log4j.Configurator.disabled=true
docx4j.jaxb.marshal.force.namespace.prefixs=true
docx4j.fonts.autodetect=true
#docx4j.Log4j.Configurator.class=org.docx4j.utils.Log4jConfigurator
docx4j.jaxb.moxy.present=true