package com.example.hotrohoctapbackend.security;

public class Endpoint {
    public static final String front_end_host = "http://localhost:3000";
    public static final String[] PUBLIC_GET_ENDPOINS = {
            "/banners",
            "/banners/**",
            "/blogcategorys",
            "/blogcategorys/**",
            "/blogs",
            "/blogs/**",
            "/categorys/",
            "/categorys/**",
            "/chapters",
            "/chapters/**",
            "/comments",
            "/comments/**",
            "/courses",
            "/courses/**",
            "/discounts",
            "/discounts/**",
            "/enrolled_courses",
            "/enrolled_courses/**",
            "/favorites",
            "/favorites/**",
            "/documents",
            "/documents/**",
            "/generaldocuments",
            "/generaldocuments/**",
            "/generaldocument_account",
            "/generaldocument_account/**",
            "/learningresult",
            "/learningresult/**",
            "/lessons",
            "/lessons/**",
            "/notifications",
            "/notifications/**",
            "/paymentdetail",
            "/paymentdetail/**",
            "/paymentmethod",
            "/paymentmethod/**",
            "/payments",
            "/payments/**",
            "/questions",
            "/questions/**",
            "/rankings",
            "/rankings/**",
            "/reviews",
            "/reviews/**",
            "/tests",
            "/tests/**",
            "/testresults",
            "/testresults/**",
            "/testuseranswers",
            "/testuseranswers/**",
            "/user_notifications",
            "/user_notifications/**",
            "/user_vipsubscriptions",
            "/user_vipsubscriptions/**",
            "/videos",
            "/videos/**",
            "/vipsubscriptions",
            "/vipsubscriptions/**",
            "/course_categories",
            "/course_categories/**",
            "/categories/level1",
            "/categories/level2",
            "/categories/level3",
            "/categories/level",

            "/api/courses",
            "/api/courses/**",
            "/api/courses/top6",
            "/api/courses/category/**",
            "/api/courses/categories",
            "/api/course-categories",
            "/api/reviews/course/**",
            "/api/courses/statistics/**",
            "/api/courses/check-type/**",
            "/api/enrolled-course/check-enrollment",

//            Thanh toán , api return gọi lại
            "/api/payment/vnpay/vn-pay-callback",

            "/courseDTO",
            "/general-document",
            "/api/general_documents",
            "/api/general_documents/**",
            "/api/general_documents/create_desc",
            "/api/general_documents/view_desc",
            "/api/general_documents/download_desc",
            "/api/general_documents/all-general-document",
            "/api/general_documents/view_desc/top6",
            "/api/general_documents/category",
            "/api/general_documents/data",
            "/api/general_documents/search",
            "/api/general_documents/search-query",
            "/api/general_documents/all",
            "/categories-all",
            "/categories/level/**",
            "/categories/parent/**",
            "/cache",
            "/cache/evict",



    };
    public static final String[] PUBLIC_POST_ENDPOINS = {
            "/account/dang-ky",
            "/account/dang-nhap",

            "/paymentdetail",
            "/paymentdetail/**",
            "/paymentmethod",
            "/paymentmethod/**",
            "/payments",
            "/payments/**",
            "/rankings",
            "/rankings/**",
            "/testresults",
            "/testresults/**",

            "/testuseranswers",
            "/testuseranswers/**",

            "/user_vipsubscriptions",
            "/user_vipsubscriptions/**",
            "/account/refresh-token"


    };
    public static final String[] PUBLIC_PUT_ENDPOINS = {
            "/user_notifications",
            "/user_notifications/**",

            "/user_vipsubscriptions",
            "/user_vipsubscriptions/**",

            //Update mat khau , cap nhat sau
            "/accounts/**",

    };

    public static final String[] PUBLIC_DELETE_ENDPOINS = {
            "/reviews",
            "/reviews/**",

            "/comments",
            "/comments/**",
    };

    public static final String[] ADMIN_GET_ENDPOINS = {
            "/accounts",
            "/accounts/**",
            "/roles",
            "/roles/**",
            "/categories/**",
            "/categories/level",
            "/categories_parent_id",
            "/name-by-id",
            "/api/general_documents/documents-with-categories",
            "/api/general_documents/generaldocuments-details/**"
    };
    public static final String[] ADMIN_POST_ENDPOINS = {
            "/accounts",
            "/accounts/**",
            "/activitylogs",
            "/activitylogs/**",
            "/roles/**",
            "/roles/**",
            "/banners",
            "/banners/**",
            "/blogcategorys",
            "/blogcategorys/**",
            "/blogs",
            "/blogs/**",
            "/categorys/",
            "/categorys/**",
            "/chapters",
            "/chapters/**",
            "/comments",
            "/comments/**",
            "/course_discounts",
            "/course_discounts/**",
            "/courses",
            "/courses/**",
            "/discounts",
            "/discounts/**",
            "/documents",
            "/documents/**",
            "/enrolled_courses",
            "/enrolled_courses/**",
            "/favorites",
            "/favorites/**",
            "/generaldocuments",
            "/generaldocuments/**",
            "/learningresult",
            "/learningresult/**",
            "/lessons",
            "/lessons/**",
            "/notifications",
            "/notifications/**",
            "/paymentdetail",
            "/paymentdetail/**",
            "/paymentmethod",
            "/paymentmethod/**",
            "/payments",
            "/payments/**",
            "/questions",
            "/questions/**",
            "/rankings",
            "/rankings/**",
            "/reviews",
            "/reviews/**",
            "/test_questions",
            "/test_questions/**",
            "/tests",
            "/tests/**",
            "/testresults",
            "/testresults/**",
            "/testuseranswers",
            "/testuseranswers/**",
            "/user_notifications",
            "/user_notifications/**",
            "/user_vipsubscriptions",
            "/user_vipsubscriptions/**",
            "/videos",
            "/videos/**",
            "/vipsubscriptions",
            "/vipsubscriptions/**",
            "/api/general_documents/upload",

            "/api/convert-docx-to-pdf",
            "/convert"
    };
    public static final String[] ADMIN_DELETE_ENDPOINS = {
            "/accounts",
            "/accounts/**",
            "/activitylogs",
            "/activitylogs/**",
            "/roles/**",
            "/roles/**",
            "/banners",
            "/banners/**",
            "/blogcategorys",
            "/blogcategorys/**",
            "/blogs",
            "/blogs/**",
            "/categorys/",
            "/categorys/**",
            "/chapters",
            "/chapters/**",
            "/comments",
            "/comments/**",
            "/course_discounts",
            "/course_discounts/**",
            "/courses",
            "/courses/**",
            "/discounts",
            "/discounts/**",
            "/documents",
            "/documents/**",
            "/enrolled_courses",
            "/enrolled_courses/**",
            "/favorites",
            "/favorites/**",
            "/generaldocuments",
            "/generaldocuments/**",
            "/learningresult",
            "/learningresult/**",
            "/lessons",
            "/lessons/**",
            "/notifications",
            "/notifications/**",
            "/paymentdetail",
            "/paymentdetail/**",
            "/paymentmethod",
            "/paymentmethod/**",
            "/payments",
            "/payments/**",
            "/questions",
            "/questions/**",
            "/rankings",
            "/rankings/**",
            "/reviews",
            "/reviews/**",
            "/test_questions",
            "/test_questions/**",
            "/tests",
            "/tests/**",
            "/testresults",
            "/testresults/**",
            "/testuseranswers",
            "/testuseranswers/**",
            "/user_notifications",
            "/user_notifications/**",
            "/user_vipsubscriptions",
            "/user_vipsubscriptions/**",
            "/videos",
            "/videos/**",
            "/vipsubscriptions",
            "/vipsubscriptions/**"
    };
    public static final String[] ADMIN_PUT_ENDPOINS = {
            "/accounts",
            "/accounts/**",
            "/activitylogs",
            "/activitylogs/**",
            "/roles/**",
            "/roles/**",
            "/banners",
            "/banners/**",
            "/blogcategorys",
            "/blogcategorys/**",
            "/blogs",
            "/blogs/**",
            "/categorys/",
            "/categorys/**",
            "/chapters",
            "/chapters/**",
            "/comments",
            "/comments/**",
            "/course_discounts",
            "/course_discounts/**",
            "/courses",
            "/courses/**",
            "/discounts",
            "/discounts/**",
            "/documents",
            "/documents/**",
            "/enrolled_courses",
            "/enrolled_courses/**",
            "/favorites",
            "/favorites/**",
            "/generaldocuments",
            "/generaldocuments/**",
            "/learningresult",
            "/learningresult/**",
            "/lessons",
            "/lessons/**",
            "/notifications",
            "/notifications/**",
            "/paymentdetail",
            "/paymentdetail/**",
            "/paymentmethod",
            "/paymentmethod/**",
            "/payments",
            "/payments/**",
            "/questions",
            "/questions/**",
            "/rankings",
            "/rankings/**",
            "/reviews",
            "/reviews/**",
            "/test_questions",
            "/test_questions/**",
            "/tests",
            "/tests/**",
            "/testresults",
            "/testresults/**",
            "/testuseranswers",
            "/testuseranswers/**",
            "/user_notifications",
            "/user_notifications/**",
            "/user_vipsubscriptions",
            "/user_vipsubscriptions/**",
            "/videos",
            "/videos/**",
            "/vipsubscriptions",
            "/vipsubscriptions/**",
            "/api/general_documents/generaldocuments-update/**"
    };


    public static final String[] USER_GET_ENDPOINT = {
            "/api/account/**",
            "/api/payment/vnpay/vn-pay",
            "/api/payments/**",
            "/api/payment-details/**"
    };

    public static final String[] USER_POST_ENDPOINT = {
            "/paymentmethod",
            "/api/payments/add",
            "/api/payment-details/add",

    };

    public static final String[] USER_PUT_ENDPOINT = {
            "/paymentmethod",
    };
    public static final String[] USER_DELETE_ENDPOINT = {
            "/paymentmethod",
    };


}
