package com.example.hotrohoctapbackend.security;

import org.springframework.beans.factory.annotation.Value;

public class Endpoint {
    //    public static final String front_end_host = "http://localhost:3000";
    @Value("*")
    private String allowedOrigins;
    public static final String[] PUBLIC_GET_ENDPOINS = {
            "/banners",
            "/banners/**",
            "/blogcategorys",
            "/blogcategorys/**",
            "/blogs",
            "/blogs/**",
            "/categorys/",
            "/categorys/**",
            "/chapters",
            "/chapters/**",
            "/comments",
            "/comments/**",
            "/courses",
            "/courses/**",
            "/discounts",
            "/discounts/**",
            "/enrolled_courses",
            "/enrolled_courses/**",
            "/favorites",
            "/favorites/**",
            "/documents",
            "/documents/**",
            "/generaldocuments",
            "/generaldocuments/**",
            "/generaldocument_account",
            "/generaldocument_account/**",
            "/learningresult",
            "/learningresult/**",
            "/lessons",
            "/lessons/**",
            "/notifications",
            "/notifications/**",
            "/paymentdetail",
            "/paymentdetail/**",
            "/paymentmethod",
            "/paymentmethod/**",
            "/payments",
            "/payments/**",
            "/questions",
            "/questions/**",
            "/rankings",
            "/rankings/**",
            "/reviews",
            "/reviews/**",
            "/tests",
            "/tests/**",
            "/testresults",
            "/testresults/**",
            "/testuseranswers",
            "/testuseranswers/**",
            "/user_notifications",
            "/user_notifications/**",
            "/user_vipsubscriptions",
            "/user_vipsubscriptions/**",
            "/videos",
            "/videos/**",
            "/vipsubscriptions",
            "/vipsubscriptions/**",
            "/course_categories",
            "/course_categories/**",
            "/categories/level1",
            "/categories/level2",
            "/categories/level3",
            "/categories/level",

            "/api/courses",
            "/api/courses/**",
            "/api/courses/top6",
            "/api/courses/category/**",
            "/api/courses/categories",
            "/api/course-categories",
            "/api/reviews/course/**",
            "/api/reviews/exam/**",
            "/api/courses/statistics/**",
            "/api/courses/check-type/**",
            "/api/enrolled-course/check-enrollment",

//            Thanh toán , api return gọi lại
            "/api/payment/vnpay/vn-pay-callback",

            "/courseDTO",
            "/general-document",

            "/api/general_documents/**",
            "/api/general_documents/create_desc",
            "/api/general_documents/view_desc",
            "/api/general_documents/download_desc",
            "/api/general_documents/all-general-document",
            "/api/general_documents/view_desc/top6",
            "/api/general_documents/category",
            "/api/general_documents/category/**",
            "/api/general_documents/data",
            "/api/general_documents/search",
            "/api/general_documents/search-query",
            "/api/general_documents/all",
            "/categories-all",
            "/categories/level/**",
            "/categories/parent/**",
            "/cache",
            "/cache/evict",
            "/ws/info",
            "/ws",
            //BLOG
            "/api/blogs",
            "/api/blogs/**",
            "/api/blog-category",
            "/api/blogs/category/**",
            "/api/blogs/newest",
            "/account/refresh-token",

            "/account/oauth2/success",
            "/api/courses/*/lessons-view",
            "/api/videos/view-user/**",
            "/api/courses/public/course-all",
            "/api/banner-voucher/list",
            "/api/categories/level3/course",
            "/api/categories/level3/blog",
            "/api/courses/public/filter",
            "/api/blogs/public",
            "/api/general_documents/public",
            "/api/tests/exam/public",
            "/api/tests/exam/public/**"

    };
    public static final String[] PUBLIC_POST_ENDPOINS = {
            "/account/dang-ky",
            "/account/dang-nhap",

            "/paymentdetail",
            "/paymentdetail/**",
            "/paymentmethod",
            "/paymentmethod/**",
            "/payments",
            "/payments/**",
            "/rankings",
            "/rankings/**",
            "/testresults",
            "/testresults/**",

            "/testuseranswers",
            "/testuseranswers/**",

            "/user_vipsubscriptions",
            "/user_vipsubscriptions/**",
            "/api/account/forgot-password",
            "/api/account/reset-password",
            "/account/register-generate",
            "/account/register-generate-sms",
            "/account/verify-otp",
            "/account/email-public"


    };
    public static final String[] PUBLIC_PUT_ENDPOINS = {
            "/user_notifications",
            "/user_notifications/**",

            "/user_vipsubscriptions",
            "/user_vipsubscriptions/**",

            //Update mat khau , cap nhat sau
            "/accounts/**",
            "/api/general_documents/*/increment-view"
    };

    public static final String[] PUBLIC_DELETE_ENDPOINS = {
            "/reviews",
            "/reviews/**",

            "/comments",
            "/comments/**",
    };

    public static final String[] ADMIN_GET_ENDPOINT = {
            "/api/discounts/new/code",
            "/api/discounts/filter-all",
            "/api/reviews/admin",
            "/api/enrolled-course/courses/*/students",
            "/api/videos/course/**",
            "/api/tests/course/**",
            "/api/lessons/course/**",
            "/api/chapters/courses/**",
            "/api/general_documents",
            "/api/categories",
            "/categories/**",
            "/categories/level",
            "/categories_parent_id",
            "/name-by-id",
            "/api/general_documents/documents-with-categories",
            "/api/general_documents/documents-with-categories-search",
            "/api/general_documents/generaldocuments-details/**",
            "/api/blogs/blogsall",
            "/api/chapters/course/**",
            "/api/payments/all",
            "/api/payment-details/payment-details/**",
            "/api/questions/export/excel",
            "/api/account",
            "/api/questions/tests/questions/**",
            "/api/tests/chitiet/**",
            "/api/account/list-all-search",
            "/api/payment-details/**",
            "/api/account/admin/**",
            "/api/chapters/admin-all",
            "/api/lessons/**",
            "/api/questions/all",
            "/api/questions/all-list",
            "/api/tests/getall",
            "/api/tests/getall-list",
            "/api/payment-details/admin/**",
            "/api/questions/detail/**",
            "/api/lessons/getall",
            "/api/comments/getall",
            "/api/courses/getallresult",
            "/api/courses/all-get-result-search",
            "/api/discounts/getall",
            "/api/discounts/detail/**",
            "/api/notifications/getall",
            "/api/courses/courses/discounts",
            "/api/courses/courses/ofaccount",
            "/api/blogs/admingetall",
            "/api/blogs/all-get-list-search",
            "/api/blogs/admin/detail/**",

            "/api/account/admin/profile/**",
            "/api/settings",
            "/api/settings/**",
            "/api/settings/type/**",

            "/api/test-results/average-scoreADMIN",
            "/api/test-results/pass-rateADMIN",
            "/api/test-results/result/detailADMIN",
            "/api/test-results/result-countADMIN",
            "/api/progress/calculateADMIN",
            "/api/enrolled-course/accounts/courses/**",
            "/api/courses/accountADMIN/enrolled/",
            "/api/enrolled-course/*/enrolled",
            "/api/backup/export",
            "/api/courses/courses/ofaccount/list/**",
            "/api/tests/course/*/chapter/*",
            "/api/payments/dashboard",
            "/api/payments/monthly-sales",
            "/api/courses/report-admin",
            "/api/courses/courses/*/check-completion",
            "/api/courses/courses/status",
            "/api/courses/courses/*/category",
            "/api/videos/list/**",
            "/api/videos/viewtest",
            "/api/payments/course-detail-admin/**",
            "/api/report/export-revenue-report",
            "/api/report/export-year",
            "/api/account/list-teacher",
            "/api/account/list-teacher-only",
            "/api/courses/get-all-result-list",
            "/api/questions/all-filter",
            "/api/questions/exam-all-filter",
            "/api/questions/all-filter-bank",
            "/api/questions/detail/checkbox",
            "/api/tests/filter-all",
            "/api/tests/filter-all-exam",
            "/api/tests/filter-all-exam-list",
            "/api/tests/detail-course-test",
            "/api/account/restore/list-all-accounts",
            "/api/account/restore/list-all/search-accounts",
            "/api/account/restore-no-delete/list-all-no-accounts-teacher",
            "/api/courses/restore/list-all-courses",
            "/api/courses/restore/list-all/search-courses",
            "/api/courses/restore-no-delete/list-all-no-courses",
            "/api/chapters/restore-no-delete/list-all-no-chapters",
            "/api/chapters/restore/list-all-chapters",
            "/api/chapters/restore/list-all/search-chapters",
            "/api/lessons/restore/list-all-lessons",
            "/api/tests/restore/list-all-tests",
            "/api/tests/deleted/list-all-exam",
            "/api/questions/restore/list-all-questions",
            "/api/general_documents/restore/list-all-documents",
            "/api/blogs/restore/list-all-blogs",
            "/api/comments/restore/list-all-comments",
            "/api/lessons/test/lesson/**",
            "/api/lessons/chapter/**",
            "/api/lessons/chapter-all/**",
            "/api/account/students/list-all-students",
            "/api/lessons/detail/**",
            "/api/test-results/check-count-test",
            "/api/banner-voucher",
            "/api/course-codes/list/**",
            "/api/student-course-data/list-student-huit/**",
            "/api/student-course-data/*/**",
            "/api/student-course-data/student/*/account/*/course/**",
            "/api/student-course-data/entity/*/*/**",
            "/api/student-course-data/dashboard/student-huit/by-course/**",
            "/api/student-course-data/students",
            "/api/student-course-data/students-list",
            "/api/student-course-data/students/detail",
            "/api/account/author",
            "/api/comments",

    };
    public static final String[] ADMIN_POST_ENDPOINS = {

            "/api/categories",
            "/api/account",
            "/activitylogs",
            "/activitylogs/**",

            "/banners",
            "/banners/**",
            "/blogcategorys",
            "/blogcategorys/**",
            "/blogs",
            "/blogs/**",
            "/categorys/",
            "/categorys/**",
            "/chapters",
            "/chapters/**",
            "/comments",
            "/comments/**",
            "/course_discounts",
            "/course_discounts/**",
            "/courses",
            "/courses/**",
            "/discounts",
            "/discounts/**",
            "/documents",
            "/documents/**",
            "/enrolled_courses",
            "/enrolled_courses/**",
            "/favorites",
            "/favorites/**",
            "/generaldocuments",
            "/generaldocuments/**",
            "/learningresult",
            "/learningresult/**",
            "/lessons",
            "/lessons/**",
            "/notifications",
            "/notifications/**",
            "/paymentdetail",
            "/paymentdetail/**",
            "/paymentmethod",
            "/paymentmethod/**",
            "/payments",
            "/payments/**",
            "/questions",
            "/questions/**",
            "/rankings",
            "/rankings/**",
            "/reviews",
            "/reviews/**",
            "/test_questions",
            "/test_questions/**",
            "/tests",
            "/tests/**",
            "/testresults",
            "/testresults/**",
            "/testuseranswers",
            "/testuseranswers/**",
            "/user_notifications",
            "/user_notifications/**",
            "/user_vipsubscriptions",
            "/user_vipsubscriptions/**",
            "/videos",
            "/videos/**",
            "/vipsubscriptions",
            "/vipsubscriptions/**",
            "/api/general_documents/upload",

            "/api/convert-docx-to-pdf",
            "/convert",
            "/api/blogs/add-branch",
            "/api/chapters/add",
            "/api/courses/add-course",
            "/api/lessons/add",
            "/api/tests/add",
            "/api/tests/add-exam",
            "/api/tests/add-list",
            "/api/tests/add-list-exam",

            "/add-branch",

            "/api/account/admin/add",
            "/api/videos/uploadVideo",
            "/api/lessons/updateLessonWithVideo",

            "/api/notifications/send",
            "/api/notifications/notify",
            "/api/course-discounts/add-discount/**",

            "/api/test-questions/add-questions/**",
            "/api/discounts/add",
            "/api/blogs/admin/add",
            "/api/settings",
            "/api/settings/**",
            "/api/backup/restore",
            "/api/blog-category",
            "/api/questions/upload-docx",
            "/api/questions/upload",
            "/api/questions/add",
            "/api/questions/export/excel-list",
            "/api/questions/export/docx-list",
            "/api/questions/add-checkbox",
            "/api/banner-voucher",
            "/api/questions/count-course",
            "/api/tests/count/tests",
            "/api/tests/add-list-exam-preparation",
            "/api/course-codes/create",
            "/api/python/send-student-data",
            "/api/student-course-data/file-upload",
            "/api/course-codes/send-course-codes",

//            "/api/student-course-data/predict",
            "/api/student-course-data/student-huit/excel/export",
            "/api/comments/reply/*"
    };
    public static final String[] ADMIN_DELETE_ENDPOINS = {
            "/api/reviews/admin/**",
            "/accounts",
            "/accounts/**",
            "/activitylogs",
            "/activitylogs/**",
            "/roles/**",
            "/roles/**",
            "/banners",
            "/banners/**",
            "/blogcategorys",
            "/blogcategorys/**",
            "/blogs",
            "/blogs/**",
            "/categorys/",
            "/categorys/**",
            "/chapters",
            "/chapters/**",
            "/comments",
            "/comments/**",
            "/course_discounts",
            "/course_discounts/**",
            "/courses",
            "/courses/**",
            "/discounts",
            "/discounts/**",
            "/documents",
            "/documents/**",
            "/enrolled_courses",
            "/enrolled_courses/**",
            "/favorites",
            "/favorites/**",
            "/generaldocuments",
            "/generaldocuments/**",
            "/learningresult",
            "/learningresult/**",
            "/lessons",
            "/lessons/**",
            "/notifications",
            "/notifications/**",
            "/paymentdetail",
            "/paymentdetail/**",
            "/paymentmethod",
            "/paymentmethod/**",
            "/payments",
            "/payments/**",
            "/questions",
            "/questions/**",
            "/rankings",
            "/rankings/**",
            "/reviews",
            "/reviews/**",
            "/test_questions",
            "/test_questions/**",
            "/tests",
            "/tests/**",
            "/testresults",
            "/testresults/**",
            "/testuseranswers",
            "/testuseranswers/**",
            "/user_notifications",
            "/user_notifications/**",
            "/user_vipsubscriptions",
            "/user_vipsubscriptions/**",
            "/videos",
            "/videos/**",
            "/vipsubscriptions",
            "/vipsubscriptions/**",
            "/api/questions",
            "/api/videos/**",
            "/api/settings",
            "/api/settings/**",
            "/api/account/admin/profile/**",
            "/api/blogs/hide",
            "/api/blogs/restore/**",
            "/api/blogs/**",
            "/api/blogs/delete",
            "/api/account/delete/**",
            "/api/courses/delete/**",
            "/api/chapters/delete/**",
            "/api/lessons/delete/**",
            "/api/tests/delete/**",
            "/api/questions/delete/**",
            "/api/general_documents/delete/**",
            "/api/blogs/delete/**",
            "/api/comments/**",
            "/api/banner-voucher/**",
            "/api/course-codes/**",
            "/api/comments/bulk"
    };
    public static final String[] ADMIN_PUT_ENDPOINS = {
            "/api/discounts/apply",
            "/api/discounts/toggle-status/**",
            "/api/reviews/admin/**",
            "/api/tests/update-exam/**",
            "/api/tests/toggle-status/**",
            "/api/tests/delete-exam/**",
            "/api/tests/restore-exam/**",
            "/api/videos/update/**",
            "/api/lessons/update/**",
            "/api/account/*/status",
            "/api/account/**",
            "/api/categories/**",
            "/accounts",
            "/accounts/**",
            "/activitylogs",
            "/activitylogs/**",
            "/roles/**",
            "/roles/**",
            "/banners",
            "/banners/**",
            "/blogcategorys",
            "/blogcategorys/**",
            "/blogs",
            "/blogs/**",
            "/categorys/",
            "/categorys/**",
            "/chapters",
            "/chapters/**",
            "/comments",
            "/comments/**",
            "/course_discounts",
            "/course_discounts/**",
            "/courses",
            "/courses/**",
            "/discounts",
            "/discounts/**",
            "/documents",
            "/documents/**",
            "/enrolled_courses",
            "/enrolled_courses/**",
            "/favorites",
            "/favorites/**",
            "/generaldocuments",
            "/generaldocuments/**",
            "/learningresult",
            "/learningresult/**",
            "/lessons",
            "/lessons/**",
            "/notifications",
            "/notifications/**",
            "/paymentdetail",
            "/paymentdetail/**",
            "/paymentmethod",
            "/paymentmethod/**",
            "/payments",
            "/payments/**",
            "/questions",
            "/questions/**",
            "/rankings",
            "/rankings/**",
            "/reviews",
            "/reviews/**",
            "/test_questions",
            "/test_questions/**",
            "/tests",
            "/tests/**",
            "/testresults",
            "/testresults/**",
            "/testuseranswers",
            "/testuseranswers/**",
            "/user_notifications",
            "/user_notifications/**",
            "/user_vipsubscriptions",
            "/user_vipsubscriptions/**",
            "/videos",
            "/videos/**",
            "/vipsubscriptions",
            "/vipsubscriptions/**",
            "/api/general_documents/generaldocuments-update/**",
            "/api/blogs/update-branch/**",
            "/api/courses/update-course/**",
            "/api/tests/**",
            "/update-branch/**",
            "/api/account/admin/**",
            "/api/account/delete/**",
            "/api/account/active/**",
            "/api/lessons/updateLessonWithVideoOrDocument",
            "/api/questions/update/**",
            "/api/questions/update-v2/**",
            "/api/questions/update-v2-checkbox/**",
            "/api/questions/copy-to-course",
            "/api/tests/delete/**",
            "/api/tests/active/**",
            "/api/lessons/delete/**",
            "/api/lessons/active/**",
            "/api/courses/delete/**",
            "/api/courses/active/**",
            "/api/questions/delete/**",
            "/api/questions/active/**",
            "/api/comments/show/**",
            "/api/comments/hide/**",
            "/api/comments/active/**",
            "/api/comments/unactive/**",
            "/api/chapters/show/**",
            "/api/chapters/hide/**",
            "/api/general_documents/show/**",
            "/api/general_documents/hide/**",
            "/api/discounts/update/**",
            "/api/discounts/show/**",
            "/api/discounts/hide/**",
            "/api/notifications/show/**",
            "/api/notifications/hide/**",
            "/api/course-discounts/reset-price",
            "/api/blogs/admin/update/**",
            "/api/tests/update-to-lesson/**",
            "/api/settings",
            "/api/settings/**",
            "/api/settings/*/activate/*",
            "/api/chapters/edit/**",
            "/api/courses/status/**",
            "/api/courses/unstatus/**",
            "/api/account/change-password-admin/**",
            "/api/account/admin/update/**",
            "/api/general_documents/status/**",
            "/api/general_documents/unstatus/**",
            "/api/account/restore/**",
            "/api/courses/restore/**",
            "/api/chapters/restore/**",
            "/api/lessons/restore/**",
            "/api/tests/restore/**",
            "/api/questions/restore/**",
            "/api/general_documents/restore/**",
            "/api/blogs/restore/**",
            "/api/comments/restore/**",
            "/api/chapters/unlock/**",
            "/api/chapters/lock/**",
            "/api/lessons/unlock/**",
            "/api/lessons/lock/**",
            "/api/lessons/excluded/**",
            "/api/lessons/add-lesson-with-video",
            "/api/lessons/updateLessonWithVideoAll",
            "/api/tests/update-not-test/**",
            "/api/banner-voucher/**",
            "/api/course-codes/update/**",
            "/api/banner-voucher/toggle-status/*",
            "/api/comments/*/status",
            "/api/comments/bulk/status"
    };


    public static final String[] USER_GET_ENDPOINT = {
            "/api/account/**",
            "/api/account/profile/**",
            "/api/payment/vnpay/vn-pay",
            "/api/payments/**",
            "/api/payment-details/**",
            "/api/enrolled-course/count/**",
            "/api/courses/account/enrolled/**",
            "/api/courses/take-course/**",
            "/api/progress/*/progress/*",
            "/api/videos/**",
            "/api/tests/**",
            "/api/tests/*/questions",
            "/api/tests/*/questions-exam",
            "/api/videos/first-video/**",
            "/api/questions/responsive-test/**",
            "/api/comments/video/*/lesson/*",
            "/api/comments/*/children/video/*/lesson/*",
            "/api/test-results/view-user",
            "/api/payments/summary",
            "/api/payments/*/details",
            "/api/general_documents/account/view-list",
            "/api/progress/calculate",
            "/api/test-results/average-score",
            "/api/test-results/pass-rate",
            "/api/test-results/result/detail",
            "/api/test-results/result-count",
            "/ws/info",
            "/ws",
            "/api/notifications/user/**",
            "/api/notifications/user/*/detail/**",
            "/api/enrolled-course/status",
            "/api/courses/*/first-chapter-lesson",
            "/api/enrolled-course/api/course-authors/**",
            "/api/test-results/download-test",
            "/api/payments/course-detail/**",
            "/api/courses/courses/status-user",
            "/api/tests/by-course",
            "/api/videos/*/lesson-chapter-ids",
            "/api/tests/*/lesson-chapter-ids"

    };

    public static final String[] USER_POST_ENDPOINT = {
            "/paymentmethod",
            "/api/payments/add",
            "/api/payment-details/add",
            "/api/enrolled-course/enroll",
            "/api/progress/add",
            "/api/test-results/add",
            "/api/user-answers/add",
            "/api/user-answers/submit",
            "/api/comments/submit",
            "/api/document-account/download",
            "/api/progress/check-pass",
            "/api/reviews/course",
//            "/api/enrolled-course/update-status"
            "/api/user-answers/exam/**",
            "/api/course-codes/enable",
            "/api/course-codes/check-enable",
            "/api/user-answers/submit-progress-no-test"
    };

    public static final String[] USER_PUT_ENDPOINT = {
            "/paymentmethod",
            "/api/account/update/**",
            "/api/account/change-password/**",
            "/api/comments/delete/**",
            "/api/notifications/mark-all-as-read/**",
            "/api/notifications/mark-as-read/**"

    };

    public static final String[] USER_DELETE_ENDPOINT = {
            "/paymentmethod",
    };
    public static final String[] HUIT_STUDENT_POST_ENDPOINT = {
            "/api/student-course-data/update",
            "/api/student-course-data/predict",
    };
    public static final String[] HUIT_STUDENT_GET_ENDPOINT = {
            "/api/prediction-result/student",
            "/api/prediction-result/student-huit-item",
    };
    public static final String[] USER_VIP_GET_ENDPOINT = {

    };
    public static final String[] USER_VIP_POST_ENDPOINT = {

    };
    public static final String[] USER_VIP_PUT_ENDPOINT = {

    };
    public static final String[] USER_VIP_DELETE_ENDPOINT = {

    };
    public static final String[] TEACHER_GET_ENDPOINT = {

    };
    public static final String[] TEACHER_POST_ENDPOINT = {


    };
    public static final String[] TEACHER_PUT_ENDPOINT = {


    };
    public static final String[] TEACHER_DELETE_ENDPOINT = {


    };

}
